package de.jplag.reporting.reportobject;

import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.Path;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

import de.jplag.reporting.reportobject.model.SubmissionMappings;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.jplag.JPlag;
import de.jplag.JPlagComparison;
import de.jplag.JPlagResult;
import de.jplag.Language;
import de.jplag.Submission;
import de.jplag.Version;
import de.jplag.options.JPlagOptions;
import de.jplag.reporting.jsonfactory.BaseCodeReportWriter;
import de.jplag.reporting.jsonfactory.ComparisonReportWriter;
import de.jplag.reporting.reportobject.mapper.ClusteringResultMapper;
import de.jplag.reporting.reportobject.mapper.MetricMapper;
import de.jplag.reporting.reportobject.model.Cluster;
import de.jplag.reporting.reportobject.model.FailedSubmission;
import de.jplag.reporting.reportobject.model.RunInformation;
import de.jplag.reporting.reportobject.model.SubmissionFile;
import de.jplag.reporting.reportobject.model.SubmissionFileIndex;
import de.jplag.reporting.reportobject.model.TopComparison;
import de.jplag.reporting.reportobject.writer.JPlagResultWriter;
import de.jplag.reporting.reportobject.writer.ZipWriter;

/**
 * Factory class, responsible for converting a JPlagResult object to Overview and Comparison DTO classes and writing it
 * to the disk.
 */
public class ReportObjectFactory {
    private static final Logger logger = LoggerFactory.getLogger(ReportObjectFactory.class);

    private static final Path DISTRIBUTION_FILE_NAME = Path.of("distribution.json");
    private static final Path RUN_INFORMATION_FILE_NAME = Path.of("runInformation.json");
    private static final Path TOP_COMPARISONS_FILE_NAME = Path.of("topComparisons.json");
    private static final Path CLUSTER_FILE_NAME = Path.of("cluster.json");
    private static final Path SUBMISSION_MAPPINGS_FILE_NAME = Path.of("submissionMappings.json");
    private static final Path README_FILE_NAME = Path.of("README.txt");
    private static final Path OPTIONS_FILE_NAME = Path.of("options.json");
    private static final String[] README_CONTENT = new String[] {"This is a software plagiarism report generated by JPlag.",
            "To view the report first get the newest version of JPlag from https://github.com/jplag/JPlag/releases/latest.",
            "Start the jar using 'java -jar jarname'. This opens a locally hosted website where you can drag this report onto the page."};

    private static final Path SUBMISSION_FILE_INDEX_FILE_NAME = Path.of("submissionFileIndex.json");
    /** Version of the report viewer. **/
    public static final Version REPORT_VIEWER_VERSION = JPlag.JPLAG_VERSION;
    private static final Path SUBMISSIONS_ROOT_PATH = Path.of("files");

    private Map<String, Map<String, String>> submissionNameToNameToComparisonFileName;

    private final JPlagResultWriter resultWriter;

    /**
     * Creates a new report object factory, that can be used to write a report.
     * @param resultWriter The writer to use for writing report content
     */
    public ReportObjectFactory(JPlagResultWriter resultWriter) {
        this.resultWriter = resultWriter;
    }

    /**
     * Creates a new report object factory, that can be used to write a report file.
     * @param targetFile The file to write the report to.
     * @throws FileNotFoundException If the file cannot be opened for writing
     */
    public ReportObjectFactory(File targetFile) throws FileNotFoundException {
        this(new ZipWriter(targetFile));
    }

    /**
     * Creates all necessary report viewer files, writes them to the disk as ZIP file with a <code>.jplag</code> extension.
     * @param result The JPlagResult to be converted into a report.
     */
    public void createAndSaveReport(JPlagResult result) {
        logger.info("Start writing report...");

        copySubmissionFilesToReport(result);

        writeComparisons(result);

        writeRunInformation(result);
        writeDistribution(result);
        writeTopComparisons(result);
        writeCluster(result);
        writeSubmissionMappings(result);

        writeSubmissionIndexFile(result);
        writeReadMeFile();
        writeOptionsFiles(result.getOptions());
        writeBaseCodeReport(result);

        this.resultWriter.close();
    }

    private void copySubmissionFilesToReport(JPlagResult result) {
        logger.info("Start to export results...");
        List<JPlagComparison> comparisons = result.getComparisons(result.getOptions().maximumNumberOfComparisons());
        Set<Submission> submissions = getSubmissions(comparisons);
        Language language = result.getOptions().language();
        for (Submission submission : submissions) {
            for (de.jplag.inputs.SubmissionFile file : submission.getFiles()) {
                Path filePath = Path.of(submission.getName()).resolve(file.relativePath());
                Path resultPath = SUBMISSIONS_ROOT_PATH.resolve(filePath);

                de.jplag.inputs.SubmissionFile fileToCopy = getFileToCopy(language, file);
                this.resultWriter.addFileContentEntry(resultPath, fileToCopy);
            }
        }
    }

    private de.jplag.inputs.SubmissionFile getFileToCopy(Language language, de.jplag.inputs.SubmissionFile file) {
        return language.useViewFiles() ? null /*(file.relativePath() + language.viewFileExtension())*/ : file; //TODO fix
    }

    private void writeComparisons(JPlagResult result) {
        ComparisonReportWriter comparisonReportWriter = new ComparisonReportWriter(this.resultWriter);
        submissionNameToNameToComparisonFileName = comparisonReportWriter.writeComparisonReports(result);
    }

    private void writeBaseCodeReport(JPlagResult result) {
        BaseCodeReportWriter baseCodeReportWriter = new BaseCodeReportWriter(this.resultWriter);
        baseCodeReportWriter.writeBaseCodeReport(result);
    }

    private void writeRunInformation(JPlagResult result) {
        List<FailedSubmission> failedSubmissions = result.getSubmissions().getInvalidSubmissions().stream()
                .map(submission -> new FailedSubmission(submission.getName(), submission.getState())).toList();
        RunInformation runInformation = new RunInformation(REPORT_VIEWER_VERSION, failedSubmissions, getDate(), result.getDuration(),
                result.getAllComparisons().size());
        this.resultWriter.addJsonEntry(runInformation, RUN_INFORMATION_FILE_NAME);
    }

    private void writeDistribution(JPlagResult result) {
        Map<String, List<Integer>> distributions = MetricMapper.getDistributions(result);
        this.resultWriter.addJsonEntry(distributions, DISTRIBUTION_FILE_NAME);
    }

    private void writeTopComparisons(JPlagResult result) {
        List<TopComparison> topComparison = new MetricMapper(Submission::getName).getTopComparisons(result);
        this.resultWriter.addJsonEntry(topComparison, TOP_COMPARISONS_FILE_NAME);
    }

    private void writeCluster(JPlagResult result) {
        List<Cluster> cluster = new ClusteringResultMapper(Submission::getName).map(result);
        this.resultWriter.addJsonEntry(cluster, CLUSTER_FILE_NAME);
    }

    private void writeSubmissionMappings(JPlagResult result) {
        SubmissionMappings mappings = new SubmissionMappings(
                result,
                submissionNameToNameToComparisonFileName);
        this.resultWriter.addJsonEntry(mappings, SUBMISSION_MAPPINGS_FILE_NAME);
    }

    private void writeReadMeFile() {
        this.resultWriter.writeStringEntry(String.join(System.lineSeparator(), README_CONTENT), README_FILE_NAME);
    }

    private void writeSubmissionIndexFile(JPlagResult result) {
        List<JPlagComparison> comparisons = result.getComparisons(result.getOptions().maximumNumberOfComparisons());
        Set<Submission> submissions = getSubmissions(comparisons);
        SubmissionFileIndex fileIndex = new SubmissionFileIndex(new HashMap<>());

        List<Map<String, Map<String, SubmissionFile>>> submissionTokenCountList = submissions.stream().parallel().map(submission -> {
            Map<String, SubmissionFile> tokenCounts = new HashMap<>();
            for (Map.Entry<de.jplag.inputs.SubmissionFile, Integer> entry : submission.getTokenCountPerFile().entrySet()) {
                String key = entry.getKey().relativePath();
                tokenCounts.put(key, new SubmissionFile(entry.getValue()));
            }
            return Map.of(submission.getName(), tokenCounts);
        }).toList();

        submissionTokenCountList.forEach(submission -> fileIndex.fileIndexes().putAll(submission));
        this.resultWriter.addJsonEntry(fileIndex, SUBMISSION_FILE_INDEX_FILE_NAME);
    }

    private void writeOptionsFiles(JPlagOptions options) {
        resultWriter.addJsonEntry(options, OPTIONS_FILE_NAME);
    }

    private Set<Submission> getSubmissions(List<JPlagComparison> comparisons) {
        Set<Submission> submissions = comparisons.stream().map(JPlagComparison::firstSubmission).collect(Collectors.toSet());
        Set<Submission> secondSubmissions = comparisons.stream().map(JPlagComparison::secondSubmission).collect(Collectors.toSet());
        submissions.addAll(secondSubmissions);
        return submissions;
    }

    private String getDate() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yy");
        Date date = new Date();
        return dateFormat.format(date);
    }
}
