export enum MetricJsonIdentifier {
  AVERAGE_SIMILARITY = 'AVG',
  MAXIMUM_SIMILARITY = 'MAX',
  MINIMUM_SIMILARITY = 'MIN',
  INTERSECTION = 'INTERSECTION',
  LONGEST_MATCH = 'LONGEST_MATCH',
  OVERALL = 'OVERALL'
}
