//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.03 at 10:46:34 AM CEST 
//


package net.s_nt.schuhmam.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * This type represents a single cluster. A cluster will contain a set of programs which are part of this specific cluster. This cluster also has got a threshold. It also has got a list of most frequent used words / tokens. If there is more than one program in the programs list the programs will added into new different clusters (left and right element). For example if there are two programs p1 and p2 in cluster A then there will be a cluster A-left and A-right. Cluster A-left will contain program p1 and cluster A-right will contain program p2.
 * 
 * <p>Java class for ClusterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClusterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="threshold" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="programs" type="{http://www.w3.org/2001/XMLSchema}IDREFS"/>
 *         &lt;element name="mostFrequentWords" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="left" type="{http://jplag.ipd.kit.edu/JPlagService/JPlagXMLResult}ClusterType" minOccurs="0"/>
 *         &lt;element name="right" type="{http://jplag.ipd.kit.edu/JPlagService/JPlagXMLResult}ClusterType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="clusterID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClusterType", propOrder = {
    "threshold",
    "programs",
    "mostFrequentWords",
    "left",
    "right"
})
public class ClusterType {

    protected float threshold;
    @XmlList
    @XmlElement(required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> programs;
    protected String mostFrequentWords;
    protected ClusterType left;
    protected ClusterType right;
    @XmlAttribute(name = "clusterID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String clusterID;

    /**
     * Gets the value of the threshold property.
     * 
     */
    public float getThreshold() {
        return threshold;
    }

    /**
     * Sets the value of the threshold property.
     * 
     */
    public void setThreshold(float value) {
        this.threshold = value;
    }

    /**
     * Gets the value of the programs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the programs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrograms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getPrograms() {
        if (programs == null) {
            programs = new ArrayList<Object>();
        }
        return this.programs;
    }

    /**
     * Gets the value of the mostFrequentWords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMostFrequentWords() {
        return mostFrequentWords;
    }

    /**
     * Sets the value of the mostFrequentWords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMostFrequentWords(String value) {
        this.mostFrequentWords = value;
    }

    /**
     * Gets the value of the left property.
     * 
     * @return
     *     possible object is
     *     {@link ClusterType }
     *     
     */
    public ClusterType getLeft() {
        return left;
    }

    /**
     * Sets the value of the left property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClusterType }
     *     
     */
    public void setLeft(ClusterType value) {
        this.left = value;
    }

    /**
     * Gets the value of the right property.
     * 
     * @return
     *     possible object is
     *     {@link ClusterType }
     *     
     */
    public ClusterType getRight() {
        return right;
    }

    /**
     * Sets the value of the right property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClusterType }
     *     
     */
    public void setRight(ClusterType value) {
        this.right = value;
    }

    /**
     * Gets the value of the clusterID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClusterID() {
        return clusterID;
    }

    /**
     * Sets the value of the clusterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClusterID(String value) {
        this.clusterID = value;
    }

}
