//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.03 at 10:46:34 AM CEST 
//


package net.s_nt.schuhmam.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A ComparisonType represents a comparison between two programs out of the submission. So it contains two program references, the avarage percentage of all single Matches of this comparison.
 * 
 * <p>Java class for ComparisonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComparisonType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="programA" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *         &lt;element name="programB" type="{http://www.w3.org/2001/XMLSchema}IDREF"/>
 *         &lt;element name="percentA" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="percentB" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="percentAverage" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="singleMatch" type="{http://jplag.ipd.kit.edu/JPlagService/JPlagXMLResult}SingleMatchType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComparisonType", propOrder = {
    "programA",
    "programB",
    "percentA",
    "percentB",
    "percentAverage",
    "singleMatch"
})
public class ComparisonType {

    @XmlElement(required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object programA;
    @XmlElement(required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object programB;
    protected float percentA;
    protected float percentB;
    protected float percentAverage;
    protected List<SingleMatchType> singleMatch;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the programA property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getProgramA() {
        return programA;
    }

    /**
     * Sets the value of the programA property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setProgramA(Object value) {
        this.programA = value;
    }

    /**
     * Gets the value of the programB property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getProgramB() {
        return programB;
    }

    /**
     * Sets the value of the programB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setProgramB(Object value) {
        this.programB = value;
    }

    /**
     * Gets the value of the percentA property.
     * 
     */
    public float getPercentA() {
        return percentA;
    }

    /**
     * Sets the value of the percentA property.
     * 
     */
    public void setPercentA(float value) {
        this.percentA = value;
    }

    /**
     * Gets the value of the percentB property.
     * 
     */
    public float getPercentB() {
        return percentB;
    }

    /**
     * Sets the value of the percentB property.
     * 
     */
    public void setPercentB(float value) {
        this.percentB = value;
    }

    /**
     * Gets the value of the percentAverage property.
     * 
     */
    public float getPercentAverage() {
        return percentAverage;
    }

    /**
     * Sets the value of the percentAverage property.
     * 
     */
    public void setPercentAverage(float value) {
        this.percentAverage = value;
    }

    /**
     * Gets the value of the singleMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the singleMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSingleMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SingleMatchType }
     * 
     * 
     */
    public List<SingleMatchType> getSingleMatch() {
        if (singleMatch == null) {
            singleMatch = new ArrayList<SingleMatchType>();
        }
        return this.singleMatch;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
