//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.03 at 10:46:34 AM CEST 
//


package net.s_nt.schuhmam.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * The class JPlagHeaderType saves information which is assigned to the entire submission and does not belong to a single submission program (SubmissionProgramType). Most parameters which were set on the first request through the web serivce call like title, sourceDirectory, language, basecode submission, etc. Those are copies of the input values of the web service: title, sourceDirectory, basecodeSubmission, limitEntries, minTokenLength, pathToFiles, readSubdirs, comparisonMode.
 * 
 * <p>Java class for JPlagHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JPlagHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sourceDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="basecodeSubmission" type="{http://www.w3.org/2001/XMLSchema}IDREF" minOccurs="0"/>
 *         &lt;element name="limitEntries" type="{http://jplag.ipd.kit.edu/JPlagService/JPlagXMLResult}LimitEntriesType"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="minTokenLength" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="languageSuffix" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="pathToFiles" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="readSubdirs" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="comparisonMode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JPlagHeaderType", propOrder = {
    "title",
    "sourceDirectory",
    "language",
    "basecodeSubmission",
    "limitEntries",
    "date",
    "minTokenLength",
    "languageSuffix",
    "pathToFiles",
    "readSubdirs",
    "comparisonMode"
})
public class JPlagHeaderType {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String sourceDirectory;
    @XmlElement(required = true)
    protected String language;
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object basecodeSubmission;
    @XmlElement(required = true)
    protected LimitEntriesType limitEntries;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    protected int minTokenLength;
    @XmlElement(required = true)
    protected List<String> languageSuffix;
    protected String pathToFiles;
    protected boolean readSubdirs;
    protected int comparisonMode;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the sourceDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceDirectory() {
        return sourceDirectory;
    }

    /**
     * Sets the value of the sourceDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceDirectory(String value) {
        this.sourceDirectory = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the basecodeSubmission property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBasecodeSubmission() {
        return basecodeSubmission;
    }

    /**
     * Sets the value of the basecodeSubmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBasecodeSubmission(Object value) {
        this.basecodeSubmission = value;
    }

    /**
     * Gets the value of the limitEntries property.
     * 
     * @return
     *     possible object is
     *     {@link LimitEntriesType }
     *     
     */
    public LimitEntriesType getLimitEntries() {
        return limitEntries;
    }

    /**
     * Sets the value of the limitEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitEntriesType }
     *     
     */
    public void setLimitEntries(LimitEntriesType value) {
        this.limitEntries = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the minTokenLength property.
     * 
     */
    public int getMinTokenLength() {
        return minTokenLength;
    }

    /**
     * Sets the value of the minTokenLength property.
     * 
     */
    public void setMinTokenLength(int value) {
        this.minTokenLength = value;
    }

    /**
     * Gets the value of the languageSuffix property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageSuffix property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageSuffix().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguageSuffix() {
        if (languageSuffix == null) {
            languageSuffix = new ArrayList<String>();
        }
        return this.languageSuffix;
    }

    /**
     * Gets the value of the pathToFiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathToFiles() {
        return pathToFiles;
    }

    /**
     * Sets the value of the pathToFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathToFiles(String value) {
        this.pathToFiles = value;
    }

    /**
     * Gets the value of the readSubdirs property.
     * 
     */
    public boolean isReadSubdirs() {
        return readSubdirs;
    }

    /**
     * Sets the value of the readSubdirs property.
     * 
     */
    public void setReadSubdirs(boolean value) {
        this.readSubdirs = value;
    }

    /**
     * Gets the value of the comparisonMode property.
     * 
     */
    public int getComparisonMode() {
        return comparisonMode;
    }

    /**
     * Sets the value of the comparisonMode property.
     * 
     */
    public void setComparisonMode(int value) {
        this.comparisonMode = value;
    }

}
