//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.03 at 10:46:34 AM CEST 
//


package net.s_nt.schuhmam.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.s_nt.schuhmam.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.s_nt.schuhmam.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link JPlagHeaderType }
     * 
     */
    public JPlagHeaderType createJPlagHeaderType() {
        return new JPlagHeaderType();
    }

    /**
     * Create an instance of {@link SubmissionProgramsType }
     * 
     */
    public SubmissionProgramsType createSubmissionProgramsType() {
        return new SubmissionProgramsType();
    }

    /**
     * Create an instance of {@link ComparisonsType }
     * 
     */
    public ComparisonsType createComparisonsType() {
        return new ComparisonsType();
    }

    /**
     * Create an instance of {@link ClusterTreeType }
     * 
     */
    public ClusterTreeType createClusterTreeType() {
        return new ClusterTreeType();
    }

    /**
     * Create an instance of {@link Result.AvgMatches }
     * 
     */
    public Result.AvgMatches createResultAvgMatches() {
        return new Result.AvgMatches();
    }

    /**
     * Create an instance of {@link Result.MinMatches }
     * 
     */
    public Result.MinMatches createResultMinMatches() {
        return new Result.MinMatches();
    }

    /**
     * Create an instance of {@link Result.MaxMatches }
     * 
     */
    public Result.MaxMatches createResultMaxMatches() {
        return new Result.MaxMatches();
    }

    /**
     * Create an instance of {@link ParserLogEntryType }
     * 
     */
    public ParserLogEntryType createParserLogEntryType() {
        return new ParserLogEntryType();
    }

    /**
     * Create an instance of {@link LimitEntriesType }
     * 
     */
    public LimitEntriesType createLimitEntriesType() {
        return new LimitEntriesType();
    }

    /**
     * Create an instance of {@link ComparisonType }
     * 
     */
    public ComparisonType createComparisonType() {
        return new ComparisonType();
    }

    /**
     * Create an instance of {@link SubmissionProgramType }
     * 
     */
    public SubmissionProgramType createSubmissionProgramType() {
        return new SubmissionProgramType();
    }

    /**
     * Create an instance of {@link MatchLocationType }
     * 
     */
    public MatchLocationType createMatchLocationType() {
        return new MatchLocationType();
    }

    /**
     * Create an instance of {@link ClusterType }
     * 
     */
    public ClusterType createClusterType() {
        return new ClusterType();
    }

    /**
     * Create an instance of {@link SingleMatchType }
     * 
     */
    public SingleMatchType createSingleMatchType() {
        return new SingleMatchType();
    }

}
