//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.03 at 10:46:34 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jplag.ipd.kit.edu/JPlagService/JPlagXMLResult", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.s_nt.schuhmam.xsd;
