//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.03 at 10:46:34 AM CEST 
//


package net.s_nt.schuhmam.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A singleMatchType represents one single match out of all found matches through the algorithm. Every match begins at a specific file location and ends at a specific file location. Additionaly there is also a numeric value which represents the number of tokens which matched in this match.
 * 
 * <p>Java class for SingleMatchType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SingleMatchType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="beginA" type="{http://jplag.ipd.kit.edu/JPlagService/JPlagXMLResult}MatchLocationType"/>
 *         &lt;element name="beginB" type="{http://jplag.ipd.kit.edu/JPlagService/JPlagXMLResult}MatchLocationType"/>
 *         &lt;element name="endA" type="{http://jplag.ipd.kit.edu/JPlagService/JPlagXMLResult}MatchLocationType"/>
 *         &lt;element name="endB" type="{http://jplag.ipd.kit.edu/JPlagService/JPlagXMLResult}MatchLocationType"/>
 *         &lt;element name="tokenCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SingleMatchType", propOrder = {
    "beginA",
    "beginB",
    "endA",
    "endB",
    "tokenCount"
})
public class SingleMatchType {

    @XmlElement(required = true)
    protected MatchLocationType beginA;
    @XmlElement(required = true)
    protected MatchLocationType beginB;
    @XmlElement(required = true)
    protected MatchLocationType endA;
    @XmlElement(required = true)
    protected MatchLocationType endB;
    protected int tokenCount;

    /**
     * Gets the value of the beginA property.
     * 
     * @return
     *     possible object is
     *     {@link MatchLocationType }
     *     
     */
    public MatchLocationType getBeginA() {
        return beginA;
    }

    /**
     * Sets the value of the beginA property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchLocationType }
     *     
     */
    public void setBeginA(MatchLocationType value) {
        this.beginA = value;
    }

    /**
     * Gets the value of the beginB property.
     * 
     * @return
     *     possible object is
     *     {@link MatchLocationType }
     *     
     */
    public MatchLocationType getBeginB() {
        return beginB;
    }

    /**
     * Sets the value of the beginB property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchLocationType }
     *     
     */
    public void setBeginB(MatchLocationType value) {
        this.beginB = value;
    }

    /**
     * Gets the value of the endA property.
     * 
     * @return
     *     possible object is
     *     {@link MatchLocationType }
     *     
     */
    public MatchLocationType getEndA() {
        return endA;
    }

    /**
     * Sets the value of the endA property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchLocationType }
     *     
     */
    public void setEndA(MatchLocationType value) {
        this.endA = value;
    }

    /**
     * Gets the value of the endB property.
     * 
     * @return
     *     possible object is
     *     {@link MatchLocationType }
     *     
     */
    public MatchLocationType getEndB() {
        return endB;
    }

    /**
     * Sets the value of the endB property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchLocationType }
     *     
     */
    public void setEndB(MatchLocationType value) {
        this.endB = value;
    }

    /**
     * Gets the value of the tokenCount property.
     * 
     */
    public int getTokenCount() {
        return tokenCount;
    }

    /**
     * Sets the value of the tokenCount property.
     * 
     */
    public void setTokenCount(int value) {
        this.tokenCount = value;
    }

}
