//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.03 at 10:46:34 AM CEST 
//


package net.s_nt.schuhmam.xsd;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The SubmissionProgramsType must contain at least two program elements (Type SubmissionProgramType).
 * 
 * <p>Java class for SubmissionProgramsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubmissionProgramsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="program" type="{http://jplag.ipd.kit.edu/JPlagService/JPlagXMLResult}SubmissionProgramType" maxOccurs="unbounded" minOccurs="2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmissionProgramsType", propOrder = {
    "program"
})
public class SubmissionProgramsType {

    @XmlElement(required = true)
    protected List<SubmissionProgramType> program;

    /**
     * Gets the value of the program property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the program property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProgram().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubmissionProgramType }
     * 
     * 
     */
    public List<SubmissionProgramType> getProgram() {
        if (program == null) {
            program = new ArrayList<SubmissionProgramType>();
        }
        return this.program;
    }
    
	public SubmissionProgramType getSubmissionProgram(String name)
	{
		List<SubmissionProgramType> l = this.getProgram();
		for (SubmissionProgramType program : l)
			if (program.getName().equals(name))
				return program;

		return null;
	}

}
