package de.jplag;

import static de.jplag.SubmissionState.CANNOT_PARSE;
import static de.jplag.SubmissionState.NOTHING_TO_PARSE;
import static de.jplag.SubmissionState.TOO_SMALL;
import static de.jplag.SubmissionState.UNPARSED;
import static de.jplag.SubmissionState.VALID;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

import de.jplag.inputs.SubmissionFile;
import de.jplag.inputs.SubmissionIdentifier;
import de.jplag.inputs.SubmissionInputData;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.jplag.commentextraction.Comment;
import de.jplag.commentextraction.CommentExtractor;
import de.jplag.commentextraction.CommentExtractorSettings;
import de.jplag.exceptions.LanguageException;
import de.jplag.normalization.TokenSequenceNormalizer;
import de.jplag.options.JPlagOptions;

/**
 * This class represents a single submission, which is either a single file or a directory containing multiple files. It
 * encapsulates the details and processing logic required to handle the submission files, including parsing,
 * tokenization, and normalization.
 */
public class Submission implements Comparable<Submission> {
    private static final Logger logger = LoggerFactory.getLogger(Submission.class);

    private final SubmissionInputData inputData;

    private final Language language;

    private SubmissionState state; // whether an error occurred during parsing or not
    private List<Token> tokenList; // list of tokens from all files, used for comparison
    private JPlagComparison baseCodeComparison; // Comparison of thus submission with the base code
    private Map<SubmissionFile, Integer> fileTokenCount;
    private final List<Comment> comments; // list of comments from all files

    public Submission(SubmissionInputData inputData, Language language) {
        this.inputData = inputData;

        this.language = language;
        tokenList = Collections.emptyList(); // Placeholder, will be replaced when submission is parsed
        comments = new ArrayList<>();
        state = UNPARSED;
    }

    /**
     * Creates a submission.
     *
     * @param name               is the identifier of the submission (directory or filename). May include parent directory name if JPlag
     *                           is executed with multiple root directories.
     * @param submissionRootFile is the submission file or the root of the submission itself.
     * @param isNew              states whether the submission must be checked for plagiarism.
     * @param files              are the files of the submissions, if the root is a single file it should just contain one file.
     * @param language           is the language of the submission.
     */
    public void Submission(String name, File submissionRootFile, boolean isNew, Collection<File> files, Language language) {
    }

    @Override
    public int compareTo(Submission other) {
        return inputData.getSubmissionIdentifier().compareTo(other.inputData.getSubmissionIdentifier());
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof Submission otherSubmission)) {
            return false;
        }
        return otherSubmission.inputData.getSubmissionIdentifier().equals(inputData.getSubmissionIdentifier());
    }

    @Override
    public int hashCode() {
        return Objects.hash(inputData.getSubmissionIdentifier());
    }

    /**
     * Provides access to the comparison of this submission to the basecode.
     *
     * @return base code comparison.
     */
    public JPlagComparison getBaseCodeComparison() {
        return baseCodeComparison;
    }

    /**
     * Provided all source code files.
     *
     * @return a collection of files this submission consists of.
     */
    public Collection<SubmissionFile> getFiles() {
        return inputData.listAllFiles();
    }

    public String getName() {
        return inputData.getName();
    }

    /**
     * @return Number of tokens in the parse result.
     */
    public int getNumberOfTokens() {
        return tokenList.size();
    }

    /**
     * The similarity divisor is used for calculating the similarity of two submissions. It is based on the token length of
     * a submission.
     *
     * @return Similarity divisor for the submission.
     */
    public int getSimilarityDivisor() {
        int divisor = getNumberOfTokens() - getFiles().size();
        if (baseCodeComparison != null) {
            divisor -= baseCodeComparison.getNumberOfMatchedTokens();
        }
        return divisor;
    }

    /**
     * @return unmodifiable list of tokens generated by parsing the submission.
     */
    public List<Token> getTokenList() {
        return tokenList;
    }

    /**
     * @return true if a comparison between the submission and the base code is available. Does not imply if there are
     * matches to the base code.
     */
    public boolean hasBaseCodeComparison() {
        return baseCodeComparison != null;
    }

    /**
     * @return true if a comparison between the submission and the base code is available. Does not imply if there are
     * matches to the base code.
     * @deprecated Use {@link #hasBaseCodeComparison()} instead.
     */
    @Deprecated(since = "6.1.0", forRemoval = true)
    public boolean hasBaseCodeMatches() {
        return baseCodeComparison != null;
    }

    /**
     * @return the state of the submissions, indicating whether it is valid or has errors.
     */
    public SubmissionState getState() {
        return state;
    }

    /**
     * @return whether the submission is new, that is, must be checked for plagiarism.
     */
    public boolean isNew() {
        return inputData.isNew();
    }

    /**
     * Sets the base code comparison.
     *
     * @param baseCodeComparison is submissions matches with the base code.
     */
    public void setBaseCodeComparison(JPlagComparison baseCodeComparison) {
        this.baseCodeComparison = baseCodeComparison;
    }

    /**
     * Sets the tokens that have been parsed from the files this submission consists of.
     *
     * @param tokenList is the list of these tokens.
     */
    public void setTokenList(List<Token> tokenList) {
        this.tokenList = Collections.unmodifiableList(new ArrayList<>(tokenList));
    }

    /**
     * String representation of the code files contained in this submission, annotated with all tokens.
     *
     * @return the annotated code as string.
     */
    public String getTokenAnnotatedSourceCode() {
        return TokenPrinterUtils.printTokensByFile(tokenList);
    }

    @Override
    public String toString() {
        return inputData.getSubmissionIdentifier().getFullyQualified();
    }

    private static File createErrorDirectory(String... subdirectoryNames) {
        File subdirectory = Path.of(JPlagOptions.ERROR_FOLDER, subdirectoryNames).toFile();
        if (!subdirectory.exists()) {
            subdirectory.mkdirs();
        }
        return subdirectory;
    }

    /**
     * Parse files of the submission.
     *
     * @param debugParser     specifies if the submission should be copied upon parsing errors.
     * @param normalize       specifies if the token sequences should be normalized.
     * @param minimalTokens   specifies the minimum number of tokens required of a valid submission.
     * @param analyzeComments specifies if comments should be extracted and analyzed.
     * @return Whether parsing was successful.
     * @throws LanguageException if the language parser is not able to parse at all.
     */
    /* package-private */ boolean parse(boolean debugParser, boolean normalize, int minimalTokens, boolean analyzeComments) throws LanguageException {
        List<SubmissionFile> files = inputData.listAllFiles();

        if (files == null || files.isEmpty()) {
            logger.error("Nothing to parse for submission \"{}\"", getName());
            state = NOTHING_TO_PARSE;
            return false;
        }

        try {
            tokenList = language.parse(inputData.getFolder(), normalize);
        } catch (CriticalParsingException e) {
            throw new LanguageException(e.getMessage(), e.getCause());
        } catch (ParsingException e) {
            logger.warn("Failed to parse submission {}:{}{}", getName(), System.lineSeparator(), e.getMessage());
            state = CANNOT_PARSE;
            return false;
        }

        if (tokenList.size() < minimalTokens) {
            // print the number of tokens without the file-end token to help users choose the right parameters:
            logger.error("Submission {} contains {} tokens, which is below the minimum match length {}!", getName(), tokenList.size() - 1, minimalTokens);
            state = TOO_SMALL;
            return false;
        }

        if (analyzeComments) {
            this.extractAndParseComments();
        }

        tokenList = Collections.unmodifiableList(tokenList);
        state = VALID;
        return true;
    }

    private void extractAndParseComments() {
        Optional<CommentExtractorSettings> commentExtractorSettings = language.getCommentExtractorSettings();
        if (commentExtractorSettings.isPresent()) {
            for (SubmissionFile file : getFiles()) {
                CommentExtractor extractor = new CommentExtractor(file, commentExtractorSettings.get());
                comments.addAll(extractor.extract());
            }
            logger.debug("Found {} comments", comments.size());
        }
    }

    /**
     * Perform token sequence normalization, which makes the token sequence invariant to dead code insertion and independent
     * statement reordering.
     */
    void normalize() {
        List<Integer> originalOrder = getOrder(tokenList);
        tokenList = TokenSequenceNormalizer.normalize(tokenList);
        List<Integer> normalizedOrder = getOrder(tokenList);

        logger.debug("original line order: {}", originalOrder);
        logger.debug("line order after normalization: {}", normalizedOrder);
        Set<Integer> normalizedSet = new HashSet<>(normalizedOrder);
        List<Integer> removed = originalOrder.stream().filter(l -> !normalizedSet.contains(l)).toList();
        logger.debug("removed {} line(s): {}", removed.size(), removed);
    }

    private List<Integer> getOrder(List<Token> tokenList) {
        List<Integer> order = new ArrayList<>(tokenList.size());  // a little too big
        int currentLineNumber = tokenList.get(0).getStartLine();
        order.add(currentLineNumber);
        for (Token token : tokenList) {
            if (token.getStartLine() != currentLineNumber) {
                currentLineNumber = token.getStartLine();
                order.add(currentLineNumber);
            }
        }
        return order;
    }

    /**
     * @return A shallow copy of this submission with the same name, root, files, etc.
     */
    public Submission copy() {
        Submission copy = new Submission(inputData, language);
        copy.setTokenList(tokenList);
        copy.setBaseCodeComparison(baseCodeComparison);
        copy.state = state;
        return copy;
    }

    /**
     * @return A mapping of each file in the submission to the number of tokens in the file
     */
    public Map<SubmissionFile, Integer> getTokenCountPerFile() {
        if (this.tokenList == null) {
            return Collections.emptyMap();
        }

        if (fileTokenCount == null) {
            fileTokenCount = new HashMap<>();
            for (SubmissionFile file : this.getFiles()) {
                fileTokenCount.put(file, 0);
            }
            for (Token token : this.tokenList) {
                fileTokenCount.put(token.getFile(), fileTokenCount.get(token.getFile()) + 1);
            }
        }
        return fileTokenCount;
    }

    public boolean matchesIdentifier(SubmissionIdentifier identifier) {
        return inputData.matchesIdentifier(identifier);
    }

    public SubmissionInputData getInputData() {
        return this.inputData;
    }
}
