export enum MetricJsonIdentifier {
  AVERAGE_SIMILARITY = 'AVG',
  MAXIMUM_SIMILARITY = 'MAX',
  LONGEST_MATCH = 'LONGEST_MATCH',
  MAXIMUM_LENGTH = 'MAXIMUM_LENGTH',
  WEIGHTED_SIMILARITY = 'WEIGHTED_SIMILARITY'
}
