<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="jplag"
    nsURI="http://www.jplag/1.0"
    nsPrefix="jplag">

  <eClassifiers xsi:type="ecore:EClass" name="PlagiarismCheck">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumSimilarity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submissions" upperBound="-1" eType="#//Submission" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1" eType="#//Comparison" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="language" eType="#//Language"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Submission">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1" eType="#//SubmissionFile" containment="true"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="SubmissionFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokenCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Comparison">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstSubmission" eType="#//Submission"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondSubmission" eType="#//Submission"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="similarity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matches" upperBound="-1" eType="#//Match" containment="true"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Match">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTokenFirst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTokenSecond" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Language">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtensions" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

</ecore:EPackage>