package de.jplag.cpp;

import de.jplag.TokenConstants;

public interface CPPTokenConstants extends TokenConstants {
    int C_BLOCK_BEGIN = 2;
    int C_BLOCK_END = 3;
    int C_SCOPE = 4;
    int C_QUESTIONMARK = 5;
    int C_ELLIPSIS = 6;
    int C_ASSIGN = 7;
    int C_DOT = 8;
    int C_ARROW = 9;
    int C_ARROWSTAR = 10;
    int C_AUTO = 11;
    int C_BREAK = 12;
    int C_CASE = 13;
    int C_CATCH = 14;
    int C_CHAR = 15;
    int C_CONST = 16;
    int C_CONTINUE = 17;
    int C_DEFAULT = 18;
    int C_DELETE = 19;
    int C_DO = 20;
    int C_DOUBLE = 21;
    int C_ELSE = 22;
    int C_ENUM = 23;
    int C_EXTERN = 24;
    int C_FLOAT = 25;
    int C_FOR = 26;
    int C_FRIEND = 27;
    int C_GOTO = 28;
    int C_IF = 29;
    int C_INLINE = 30;
    int C_INT = 31;
    int C_LONG = 32;
    int C_NEW = 33;
    int C_PRIVATE = 34;
    int C_PROTECTED = 35;
    int C_PUBLIC = 36;
    int C_REDECLARED = 37;
    int C_REGISTER = 38;
    int C_RETURN = 39;
    int C_SHORT = 40;
    int C_SIGNED = 41;
    int C_SIZEOF = 42;
    int C_STATIC = 43;
    int C_STRUCT = 44;
    int C_CLASS = 45;
    int C_SWITCH = 46;
    int C_TEMPLATE = 47;
    int C_THIS = 48;
    int C_TRY = 49;
    int C_TYPEDEF = 50;
    int C_UNION = 51;
    int C_UNSIGNED = 52;
    int C_VIRTUAL = 53;
    int C_VOID = 54;
    int C_VOLANTILE = 55;
    int C_WHILE = 56;
    int C_OPERATOR = 57;
    int C_THROW = 58;
    int C_ID = 59;
    int C_FUN = 60;
    int C_DOTSTAR = 61;
    int C_NULL = 62;

    int NUM_DIFF_TOKENS = 63;
}
