package de.jplag.python3;

import static de.jplag.python3.Python3TokenType.APPLY;
import static de.jplag.python3.Python3TokenType.ARRAY;
import static de.jplag.python3.Python3TokenType.ASSERT;
import static de.jplag.python3.Python3TokenType.ASSIGN;
import static de.jplag.python3.Python3TokenType.ASYNC;
import static de.jplag.python3.Python3TokenType.AWAIT;
import static de.jplag.python3.Python3TokenType.BREAK;
import static de.jplag.python3.Python3TokenType.CASE;
import static de.jplag.python3.Python3TokenType.CLASS_BEGIN;
import static de.jplag.python3.Python3TokenType.CLASS_END;
import static de.jplag.python3.Python3TokenType.COMPREHENSION;
import static de.jplag.python3.Python3TokenType.CONTINUE;
import static de.jplag.python3.Python3TokenType.DEC_BEGIN;
import static de.jplag.python3.Python3TokenType.DEC_END;
import static de.jplag.python3.Python3TokenType.DEL;
import static de.jplag.python3.Python3TokenType.EXCEPT_BEGIN;
import static de.jplag.python3.Python3TokenType.EXCEPT_END;
import static de.jplag.python3.Python3TokenType.FINALLY;
import static de.jplag.python3.Python3TokenType.FOR_BEGIN;
import static de.jplag.python3.Python3TokenType.FOR_END;
import static de.jplag.python3.Python3TokenType.IF_BEGIN;
import static de.jplag.python3.Python3TokenType.IF_END;
import static de.jplag.python3.Python3TokenType.IMPORT;
import static de.jplag.python3.Python3TokenType.LAMBDA;
import static de.jplag.python3.Python3TokenType.MATCH_BEGIN;
import static de.jplag.python3.Python3TokenType.MATCH_END;
import static de.jplag.python3.Python3TokenType.METHOD_BEGIN;
import static de.jplag.python3.Python3TokenType.METHOD_END;
import static de.jplag.python3.Python3TokenType.RAISE;
import static de.jplag.python3.Python3TokenType.RETURN;
import static de.jplag.python3.Python3TokenType.TRY_BEGIN;
import static de.jplag.python3.Python3TokenType.WALRUS;
import static de.jplag.python3.Python3TokenType.WHILE_BEGIN;
import static de.jplag.python3.Python3TokenType.WHILE_END;
import static de.jplag.python3.Python3TokenType.WITH_BEGIN;
import static de.jplag.python3.Python3TokenType.WITH_END;
import static de.jplag.python3.Python3TokenType.YIELD;

import de.jplag.antlr.AbstractAntlrListener;
import de.jplag.python3.grammar.Python3Parser;
import de.jplag.python3.grammar.Python3Parser.Assert_stmtContext;
import de.jplag.python3.grammar.Python3Parser.AugassignContext;
import de.jplag.python3.grammar.Python3Parser.Class_def_rawContext;
import de.jplag.python3.grammar.Python3Parser.DecoratorsContext;
import de.jplag.python3.grammar.Python3Parser.Del_stmtContext;
import de.jplag.python3.grammar.Python3Parser.DictContext;
import de.jplag.python3.grammar.Python3Parser.SetContext;
import de.jplag.python3.grammar.Python3Parser.Except_blockContext;
import de.jplag.python3.grammar.Python3Parser.For_stmtContext;
import de.jplag.python3.grammar.Python3Parser.Function_def_rawContext;
import de.jplag.python3.grammar.Python3Parser.If_stmtContext;
import de.jplag.python3.grammar.Python3Parser.Import_stmtContext;
import de.jplag.python3.grammar.Python3Parser.LambdefContext;
import de.jplag.python3.grammar.Python3Parser.Match_stmtContext;
import de.jplag.python3.grammar.Python3Parser.Raise_stmtContext;
import de.jplag.python3.grammar.Python3Parser.Return_stmtContext;
import de.jplag.python3.grammar.Python3Parser.PrimaryContext;
import de.jplag.python3.grammar.Python3Parser.Try_stmtContext;
import de.jplag.python3.grammar.Python3Parser.While_stmtContext;
import de.jplag.python3.grammar.Python3Parser.With_stmtContext;
import de.jplag.python3.grammar.Python3Parser.Yield_exprContext;
import de.jplag.python3.grammar.Python3Parser.Yield_stmtContext;

import de.jplag.python3.grammar.Python3Parser.AssignmentContext;
import de.jplag.python3.grammar.Python3Parser.Kwarg_or_starredContext;
import de.jplag.python3.grammar.Python3Parser.KwdsContext;
import de.jplag.python3.grammar.Python3Parser.Case_blockContext;
import de.jplag.python3.grammar.Python3Parser.Named_expressionContext;
import de.jplag.python3.grammar.Python3Parser.ListcompContext;
import de.jplag.python3.grammar.Python3Parser.SetcompContext;
import de.jplag.python3.grammar.Python3Parser.DictcompContext;

/**
 * Listener for traversing Python parse trees generated by ANTLR.
 */
public class PythonListener extends AbstractAntlrListener {

    /**
     * Constructs a new listener.
     */
    public PythonListener() {
        statements();
        controlStructures();
        contexts();
        values();
    }

    private void statements() {
        visit(Assert_stmtContext.class).map(ASSERT);
        visit(Raise_stmtContext.class).map(RAISE);
        visit(Return_stmtContext.class).map(RETURN);
        visit(Yield_exprContext.class).map(YIELD);
        visit(Yield_stmtContext.class).map(YIELD);
        visit(Import_stmtContext.class).map(IMPORT);
        visit(Python3Parser.BREAK).map(BREAK);
        visit(Python3Parser.CONTINUE).map(CONTINUE);
        visit(Del_stmtContext.class).map(DEL);
        visit(Python3Parser.FINALLY).map(FINALLY);

        visit(Python3Parser.ASYNC).map(ASYNC);
        visit(Python3Parser.AWAIT).map(AWAIT);

        visit(Except_blockContext.class).map(EXCEPT_BEGIN, EXCEPT_END);
    }

    private void controlStructures() {
        visit(While_stmtContext.class).map(WHILE_BEGIN, WHILE_END);
        visit(Try_stmtContext.class).map(TRY_BEGIN);
        visit(If_stmtContext.class).map(IF_BEGIN, IF_END);
        visit(With_stmtContext.class).map(WITH_BEGIN, WITH_END);
        visit(For_stmtContext.class).map(FOR_BEGIN, FOR_END);

        visit(Match_stmtContext.class).map(MATCH_BEGIN, MATCH_END);
        visit(Case_blockContext.class).map(CASE);
    }

    private void contexts() {
        visit(DecoratorsContext.class).map(DEC_BEGIN, DEC_END);
        visit(LambdefContext.class).map(LAMBDA);
        visit(Class_def_rawContext.class).map(CLASS_BEGIN, CLASS_END);
        visit(Function_def_rawContext.class).map(METHOD_BEGIN, METHOD_END);
    }

    private void values() {
        visit(DictContext.class).map(ARRAY);
        visit(SetContext.class).map(ARRAY);
        visit(AugassignContext.class).map(ASSIGN);
        visit(AssignmentContext.class).map(ASSIGN);

        visit(Kwarg_or_starredContext.class).map(ASSIGN);
        visit(KwdsContext.class).map(ASSIGN);

        visit(Python3Parser.LPAR).map(APPLY);
        visit(PrimaryContext.class, ctx -> ctx.DOT() != null).map(ARRAY);

        visit(Named_expressionContext.class).map(WALRUS);

        visit(SetcompContext.class).map(COMPREHENSION);
        visit(DictcompContext.class).map(COMPREHENSION);
        visit(ListcompContext.class).map(COMPREHENSION);
    }
}