package de.jplag.python3;

import static de.jplag.python3.Python3TokenType.APPLY;
import static de.jplag.python3.Python3TokenType.ARRAY;
import static de.jplag.python3.Python3TokenType.ASSERT;
import static de.jplag.python3.Python3TokenType.ASSIGN;
import static de.jplag.python3.Python3TokenType.ASYNC;
import static de.jplag.python3.Python3TokenType.AWAIT;
import static de.jplag.python3.Python3TokenType.BREAK;
import static de.jplag.python3.Python3TokenType.CLASS_BEGIN;
import static de.jplag.python3.Python3TokenType.CLASS_END;
import static de.jplag.python3.Python3TokenType.CONTINUE;
import static de.jplag.python3.Python3TokenType.DEC_BEGIN;
import static de.jplag.python3.Python3TokenType.DEC_END;
import static de.jplag.python3.Python3TokenType.DEL;
import static de.jplag.python3.Python3TokenType.EXCEPT_BEGIN;
import static de.jplag.python3.Python3TokenType.EXCEPT_END;
import static de.jplag.python3.Python3TokenType.FINALLY;
import static de.jplag.python3.Python3TokenType.FOR_BEGIN;
import static de.jplag.python3.Python3TokenType.FOR_END;
import static de.jplag.python3.Python3TokenType.IF_BEGIN;
import static de.jplag.python3.Python3TokenType.IF_END;
import static de.jplag.python3.Python3TokenType.IMPORT;
import static de.jplag.python3.Python3TokenType.LAMBDA;
import static de.jplag.python3.Python3TokenType.METHOD_BEGIN;
import static de.jplag.python3.Python3TokenType.METHOD_END;
import static de.jplag.python3.Python3TokenType.RAISE;
import static de.jplag.python3.Python3TokenType.RETURN;
import static de.jplag.python3.Python3TokenType.TRY_BEGIN;
import static de.jplag.python3.Python3TokenType.WHILE_BEGIN;
import static de.jplag.python3.Python3TokenType.WHILE_END;
import static de.jplag.python3.Python3TokenType.WITH_BEGIN;
import static de.jplag.python3.Python3TokenType.WITH_END;
import static de.jplag.python3.Python3TokenType.YIELD;

import de.jplag.antlr.AbstractAntlrListener;
import de.jplag.python3.grammar.PythonParser;
import de.jplag.python3.grammar.PythonParser.Assert_stmtContext;
import de.jplag.python3.grammar.PythonParser.AugassignContext;
import de.jplag.python3.grammar.PythonParser.Class_defContext;
import de.jplag.python3.grammar.PythonParser.DecoratorsContext;
import de.jplag.python3.grammar.PythonParser.Del_stmtContext;
import de.jplag.python3.grammar.PythonParser.DictContext;
import de.jplag.python3.grammar.PythonParser.Except_blockContext;
import de.jplag.python3.grammar.PythonParser.For_stmtContext;
import de.jplag.python3.grammar.PythonParser.Function_defContext;
import de.jplag.python3.grammar.PythonParser.If_stmtContext;
import de.jplag.python3.grammar.PythonParser.Import_stmtContext;
import de.jplag.python3.grammar.PythonParser.LambdefContext;
import de.jplag.python3.grammar.PythonParser.PrimaryContext;
import de.jplag.python3.grammar.PythonParser.Raise_stmtContext;
import de.jplag.python3.grammar.PythonParser.Return_stmtContext;
import de.jplag.python3.grammar.PythonParser.Try_stmtContext;
import de.jplag.python3.grammar.PythonParser.TupleContext;
import de.jplag.python3.grammar.PythonParser.While_stmtContext;
import de.jplag.python3.grammar.PythonParser.With_stmtContext;
import de.jplag.python3.grammar.PythonParser.Yield_exprContext;
import de.jplag.python3.grammar.PythonParser.Yield_stmtContext;

/**
 * Listener for traversing Python parse trees generated by ANTLR.
 */
public class PythonListener extends AbstractAntlrListener {

    /**
     * Constructs a new listener.
     */
    public PythonListener() {
        statements();
        controlStructures();
        contexts();
        values();
    }

    private void statements() {
        visit(Assert_stmtContext.class).map(ASSERT);
        visit(Raise_stmtContext.class).map(RAISE);
        visit(Return_stmtContext.class).map(RETURN);
        visit(Yield_exprContext.class).map(YIELD);
        visit(Yield_stmtContext.class).map(YIELD);
        visit(Import_stmtContext.class).map(IMPORT);
        visit(PythonParser.BREAK).map(BREAK);
        visit(PythonParser.CONTINUE).map(CONTINUE);
        visit(Del_stmtContext.class).map(DEL);
        visit(PythonParser.FINALLY).map(FINALLY);

        visit(PythonParser.ASYNC).map(ASYNC);
        visit(PythonParser.AWAIT).map(AWAIT);

        visit(Except_blockContext.class).map(EXCEPT_BEGIN, EXCEPT_END);
    }

    private void controlStructures() {
        visit(While_stmtContext.class).map(WHILE_BEGIN, WHILE_END);
        visit(Try_stmtContext.class).map(TRY_BEGIN);
        visit(If_stmtContext.class).map(IF_BEGIN, IF_END);
        visit(With_stmtContext.class).map(WITH_BEGIN, WITH_END);
        visit(For_stmtContext.class).map(FOR_BEGIN, FOR_END);
    }

    private void contexts() {
        visit(DecoratorsContext.class).map(DEC_BEGIN, DEC_END);
        visit(LambdefContext.class).map(LAMBDA);
        visit(Class_defContext.class).map(CLASS_BEGIN, CLASS_END);
        visit(Function_defContext.class).delegateContext(context -> context.function_def_raw().block()).map(METHOD_BEGIN, METHOD_END);
    }

    private void values() {
        visit(DictContext.class).map(ARRAY);
        visit(TupleContext.class).map(ARRAY);
        visit(AugassignContext.class).map(ASSIGN);
        visit(PythonParser.EQUAL).map(ASSIGN);

        visit(PrimaryContext.class, primary -> primary.LPAR() != null).map(APPLY);
        // visit(TrailerContext.class, ctx -> ctx.getText().charAt(0) != '(').map(ARRAY);
    }
}
