package de.jplag.rust.grammar;

import org.antlr.v4.runtime.Parser;
import org.antlr.v4.runtime.TokenStream;

/**
 * Abstract base class for a Rust parser generated by ANTLR.
 */
public abstract class RustParserBase extends Parser {
    protected RustParserBase(TokenStream input) {
        super(input);
    }

    /**
     * Performs a one-character lookahead in the input stream to check if the next character matches the expected character.
     * @param expect the expected character
     * @return true if the next character matches; false otherwise
     */
    public boolean next(char expect) {
        return _input.LA(1) == expect;
    }
}