name: main and develop SonarCloud Scan

on:
  push:
    branches:
      - main
      - develop
    paths:
      - ".github/workflows/check-sonarcloud-main-develop.yml"
      - "**/pom.xml"
      - "**.java"
      - "**.g4"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - run: |
          download_url="https://github.com/JFronny/jdk-babylon/releases/download/artifacts/bundles-linux-x64.zip"
          wget -O $RUNNER_TEMP/java_bundle.zip $download_url
          7z x $RUNNER_TEMP/java_bundle.zip -o$RUNNER_TEMP
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: jdkfile
          jdkFile: ${{ runner.temp }}/jdk-linux-x64.tar.gz
          java-version: 26

      - name: Cache SonarCloud packages
        uses: actions/cache@v6
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -U -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
