name: Close Issue on PR Merge

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read
  issues: write

jobs:
  close_issues:
    if: github.event.pull_request.merged == true && github.base_ref == 'develop'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
    - name: Run script
      working-directory: .github/workflows/scripts
      run: |
        pip install requests
        python closeDevIssues.py ${{ secrets.GITHUB_TOKEN }} jplag JPlag ${{ github.event.pull_request.number }}