name: Match Report Schema

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/match-record-to-interface.yml"
      - ".github/workflows/scripts/matchRecordToInterface.py"
      - "report-viewer/**"
      - "**.java"

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

  check_matches:
    runs-on: ubuntu-latest
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4
      
    - name: Run script
      working-directory: .github/workflows/scripts
      run: |
        python matchRecordToInterface.py
