name: Publish Release
on:
  workflow_dispatch:
  release:
    types: [created, published]
permissions:
  contents: read

jobs:
  publish-maven-central:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Set maven settings.xml
        uses: whelk-io/maven-settings-xml-action@9dc09b23833fa9aa7f27b63db287951856f3433d # v22
        with:
          servers: '[{ "id": "central", "username": "${{ secrets.CENTRAL_USER }}", "password": "${{ secrets.CENTRAL_TOKEN }}" }]'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
      - name: Publish package
        run: mvn -P deployment -U -B deploy

  publish-release-artifact:
    # softprops/action-gh-release uploads the artifact to the release.
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: '25'
          distribution: 'temurin'
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "lts/*"

      - name: Set version of Report Viewer
        shell: bash
        run: |
          VERSION=$(grep "<revision>" pom.xml | grep -oPm1 "(?<=<revision>)[^-|<]+")
          MAJOR=$(echo $VERSION | cut -d '.' -f 1)
          MINOR=$(echo $VERSION | cut -d '.' -f 2)
          PATCH=$(echo $VERSION | cut -d '.' -f 3)
          json=$(cat report-viewer/report-viewer/src/version/version.json)
          json=$(echo "$json" | jq --arg MAJOR "$MAJOR" --arg MINOR "$MINOR" --arg PATCH "$PATCH" '.report_viewer_version |= { "major": $MAJOR | tonumber, "minor": $MINOR | tonumber, "patch": $PATCH | tonumber }')
          echo "$json" >  report-viewer/report-viewer/src/version/version.json
          echo "Version of Report Viewer:"
          cat report-viewer/report-viewer/src/version/version.json

      - name: Build JPlag
        run: mvn -Pwith-report-viewer -U -B clean package assembly:single

      - name: Attach CLI to Release on GitHub
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cli/target/jplag-*-jar-with-dependencies.jar
          fail_on_unmatched_files: true
