name: Report Viewer ESLint


on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/report-viewer-check-lint.yml"
      - "report-viewer/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/report-viewer-lint.yml"
      - "report-viewer/**"
      
jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@b974a9395958c231af965b70070979a577efa578 # v5.3.2
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

  check:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "lts/*"

      - name: Install and Lint 🎨
        working-directory: report-viewer
        run: |
          npm install
          npm run lint
