name: Report Viewer Unit Test / SonarCloud

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - "report-viewer/**"
      - ".github/workflows/report-viewer-test-unit-and-check-sonarcloud.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "report-viewer/**"
      - ".github/workflows/report-viewer-test-unit-and-check-sonarcloud.yml"

permissions:
  contents: read

jobs:
  pre_job:
    # skip-duplicate-actions documents actions:write + contents:read
    # as its minimum.
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@b974a9395958c231af965b70070979a577efa578 # v5.3.2
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

  test_and_sonarcloud:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "lts/*"

      - name: Install
        working-directory: report-viewer
        run: |
          npm install
      - name: Test model
        working-directory: report-viewer/model
        run: |
          npm run test
      - name: Test parser
        working-directory: report-viewer/parser
        run: |
          npm run test
      - name: Test ui-components
        working-directory: report-viewer/ui-components
        run: |
          npm run test
      - name: Test report-viewer
        working-directory: report-viewer/report-viewer
        run: |
          npm run test:unit
      
      - name: SonarCloud Scan
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.head.repo.owner.login == 'jplag' }}
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        with:
          projectBaseDir: report-viewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_REPORT_VIEWER }}
