name: Deploy Dev Report Viewer

on:
 workflow_dispatch: # Use this to dispatch from the Actions Tab
 push:
    branches:
      - develop
    paths:
      - ".github/workflows/report-viewer-deploy-develop.yml"
      - "report-viewer/**"
      
# The pages deploy pushes to a branch.
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "lts/*"

      - name: Install and Build 🔧
        working-directory: report-viewer/report-viewer
        run: |
          npm install
          npm run build-dev

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: report-viewer/report-viewer/dist
          repository-name: JPlag/JPlag-Dev
          token: ${{ secrets.SDQ_DEV_DEPLOY_TOKEN }}
          clean: true
          single-commit: true
