name: Report Viewer ESLint Workflow # Checks linting of report viewer


on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/report-viewer-lint.yml"
      - "report-viewer/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/report-viewer-lint.yml"
      - "report-viewer/**"
      
jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

  check:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install and Lint 🎨
        working-directory: report-viewer
        run: |
          npm install
          npm run lint
